test:
  adapter: postgresql
  username: postgres
  password:
  database: ffn_api_test
  min_messages: ERROR
  
production:
  adapter: postgresql
  encoding: utf8
  database: sammy
  username: sammydb
  password: password
  host: 165.227.196.28
  port: 5432
  pool: 10