require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VouchersController do

  # This should return the minimal set of attributes required to create a valid
  # Voucher. As you add validations to Voucher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "redeemed" => "false" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VouchersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vouchers as @vouchers" do
      voucher = Voucher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vouchers).should eq([voucher])
    end
  end

  describe "GET show" do
    it "assigns the requested voucher as @voucher" do
      voucher = Voucher.create! valid_attributes
      get :show, {:id => voucher.to_param}, valid_session
      assigns(:voucher).should eq(voucher)
    end
  end

  describe "GET new" do
    it "assigns a new voucher as @voucher" do
      get :new, {}, valid_session
      assigns(:voucher).should be_a_new(Voucher)
    end
  end

  describe "GET edit" do
    it "assigns the requested voucher as @voucher" do
      voucher = Voucher.create! valid_attributes
      get :edit, {:id => voucher.to_param}, valid_session
      assigns(:voucher).should eq(voucher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Voucher" do
        expect {
          post :create, {:voucher => valid_attributes}, valid_session
        }.to change(Voucher, :count).by(1)
      end

      it "assigns a newly created voucher as @voucher" do
        post :create, {:voucher => valid_attributes}, valid_session
        assigns(:voucher).should be_a(Voucher)
        assigns(:voucher).should be_persisted
      end

      it "redirects to the created voucher" do
        post :create, {:voucher => valid_attributes}, valid_session
        response.should redirect_to(Voucher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voucher as @voucher" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voucher.any_instance.stub(:save).and_return(false)
        post :create, {:voucher => { "redeemed" => "invalid value" }}, valid_session
        assigns(:voucher).should be_a_new(Voucher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voucher.any_instance.stub(:save).and_return(false)
        post :create, {:voucher => { "redeemed" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voucher" do
        voucher = Voucher.create! valid_attributes
        # Assuming there are no other vouchers in the database, this
        # specifies that the Voucher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Voucher.any_instance.should_receive(:update).with({ "redeemed" => "false" })
        put :update, {:id => voucher.to_param, :voucher => { "redeemed" => "false" }}, valid_session
      end

      it "assigns the requested voucher as @voucher" do
        voucher = Voucher.create! valid_attributes
        put :update, {:id => voucher.to_param, :voucher => valid_attributes}, valid_session
        assigns(:voucher).should eq(voucher)
      end

      it "redirects to the voucher" do
        voucher = Voucher.create! valid_attributes
        put :update, {:id => voucher.to_param, :voucher => valid_attributes}, valid_session
        response.should redirect_to(voucher)
      end
    end

    describe "with invalid params" do
      it "assigns the voucher as @voucher" do
        voucher = Voucher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voucher.any_instance.stub(:save).and_return(false)
        put :update, {:id => voucher.to_param, :voucher => { "redeemed" => "invalid value" }}, valid_session
        assigns(:voucher).should eq(voucher)
      end

      it "re-renders the 'edit' template" do
        voucher = Voucher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voucher.any_instance.stub(:save).and_return(false)
        put :update, {:id => voucher.to_param, :voucher => { "redeemed" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voucher" do
      voucher = Voucher.create! valid_attributes
      expect {
        delete :destroy, {:id => voucher.to_param}, valid_session
      }.to change(Voucher, :count).by(-1)
    end

    it "redirects to the vouchers list" do
      voucher = Voucher.create! valid_attributes
      delete :destroy, {:id => voucher.to_param}, valid_session
      response.should redirect_to(vouchers_url)
    end
  end

end
